### ISSUE TITLE
Double the id when creating 2 fields of the same type.

### ISSUE THREAD

**Issue by andyhoanghuu** [truongwp/puppyfw#2]
When creating 2 fields of the same type, their id is doubled.
You can see my screenshots:
![dbid](https://user-images.githubusercontent.com/19216611/30689957-d3483c74-9eec-11e7-8e7c-f8fec85ab207.png)
![double-id](https://user-images.githubusercontent.com/19216611/30689985-e50cd38e-9eec-11e7-8697-19421a40dccc.png)

**Comment by truongwp** [comment]
Hi @ndoublehwp,
Can you give me the code you use to define two image fields? I tested but didn't found the problem.
Thanks.

**Comment by truongwp** [comment]
Hi @ndoublehwp,

Those ids is different: `image` and `images` :D
